from app.models import User, Products
from app import db

u1 = User(username='tv show', email='v1@v1.com')
db.session.add(u1)
u2 = User(username='country', email='v2@v2.com')
db.session.add(u2)
u3 = User(username='colours', email='v3@v3.com')
db.session.add(u3)

p = Products(p_name='suits season 1', p_price='5', p_picture = 'http://ecx.images-amazon.com/images/I/61XzKzRzONL._SL1073_.jpg', users=u1)
db.session.add(p)
p = Products(p_name='suits season 2', p_price='5', p_picture = 'http://ecx.images-amazon.com/images/I/91ziEZy5iIL._SL1500_.jpg', users=u1)
db.session.add(p)
p = Products(p_name='suits season 3', p_price='5', p_picture = 'http://ecx.images-amazon.com/images/I/81lZwVSwazL._SY550_.jpg', users=u1)
db.session.add(p)
p = Products(p_name='suits season 4', p_price='5', p_picture = 'NULL', users=u1)
db.session.add(p)
p = Products(p_name='white collar season 1', p_price='5', p_picture = 'http://ecx.images-amazon.com/images/I/81v-hQPttNL._SY550_.jpg', users=u1)
db.session.add(p)
p = Products(p_name='white collar season 2', p_price='5', p_picture = 'NULL', users=u1)
db.session.add(p)
p = Products(p_name='white collar season 3', p_price='5', p_picture = 'http://ecx.images-amazon.com/images/I/61Yy-HdCjcL._SL1107_.jpg', users=u1)
db.session.add(p)
p = Products(p_name='white collar season 4', p_price='5', p_picture = 'http://ecx.images-amazon.com/images/I/61mRuUaW6JL._SL1121_.jpg', users=u1)
db.session.add(p)
p = Products(p_name='white collar season 5', p_price='5', p_picture = 'NULL', users=u1)
db.session.add(p)
p = Products(p_name='white collar season 6', p_price='5', p_picture = 'NULL', users=u1)
db.session.add(p)
p = Products(p_name='white queen', p_price='5', users=u1)
db.session.add(p)


p = Products(p_name='Canada', p_price='2', users=u2)
db.session.add(p)
p = Products(p_name='England', p_price='2', users=u2)
db.session.add(p)
p = Products(p_name='Spain', p_price='2', users=u2)
db.session.add(p)
p = Products(p_name='Greece', p_price='2', users=u2)
db.session.add(p)

p = Products(p_name='black', p_price='12', p_picture = 'https://media2.wnyc.org/i/620/372/l/80/1/blackbox.jpeg', users=u3)
db.session.add(p)
p = Products(p_name='red', p_price='12', p_picture = 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Red.svg/120px-Red.svg.png', users=u3)
db.session.add(p)
p = Products(p_name='white', p_price='12', users=u3)
db.session.add(p)
p = Products(p_name='purple', p_price='12', users=u3)
db.session.add(p)

db.session.commit()